<?= $this->insert('overall/header')?>

<body>

<?= $this->insert('overall/topnav')?>

  <div class="ts-main-content">

    <?= $this->insert('overall/menu')?>

    <div class="content-wrapper">
      <div class="container-fluid">

        <div class="row">
          <div class="col-md-12">
          
            <h1 class="page-title">Proveedor</h1>

            <h2>Creación</h2>
            
            <div class="col-lg-2"></div>
            <div class="well col-lg-8">
              <div class="form-actions">
                <div class="panel panel-default">
                  <div class="panel-heading">Crear Proveedor</div>
                  <div class="panel-body">
                    <form id="proveedor_form" role="form">
                      <div class="alert hide" id="ajax_proveedor"></div>

                      <div class="col-lg-4 form-group">
                        <label class="cole">Nit:</label>
                        <input type="text" class="form-control form-input" name="nit" placeholder="Escribe el nit..." />
                      </div>

                      <div class="col-lg-4 form-group">
                        <label class="cole">Nombre:</label>
                        <input type="text" class="form-control form-input" name="nombre" placeholder="Escribe el nombre..." />
                      </div>

                      <div class="col-lg-4 form-group">
                        <label class="cole">Dirección:</label>
                        <input type="text" class="form-control form-input" name="direccion" placeholder="Escribe la dirección..." />
                      </div>

                      <div class="col-lg-4 form-group">
                        <label class="cole">Teléfono:</label>
                        <input type="text" class="form-control form-input" name="telefono" placeholder="Escribe el teléfono..." />
                      </div>

                      <div class="col-lg-4 form-group">
                        <label class="cole">Correo electrónico:</label>
                        <input type="text" class="form-control form-input" name="correo" placeholder="Escribe el correo electrónico..." />
                      </div>

                      <div class="col-lg-4 form-group">
                        <label class="cole">Sitio web:</label>
                        <input type="text" class="form-control form-input" name="web" placeholder="Escribe la página web..." />
                      </div>
                      
                      <div class="col-lg-4 form-group">
                        <label class="cole">Estado:</label>
                        <select class="form-control" name="estado">
                          <option value="AC">Activo</option>
                          <option value="IN">Inactivo</option>
                        </select> 
                      </div>

                      <div class="col-lg-12">
                        <div class="form-group">
                          <button type="button" id="proveedor" class="btn btn-primary  center-block">Enviar</button>
                        </div>
                      </div>
                    </form>
                  </div>

                </div>
                

              </div>
              <a class="btn btn-primary" href="proveedor">Ver listado</a>
            </div>
            <div class="col-lg-2"></div> 
            
          </div>
        </div>
        
        <?= $this->insert('overall/inner_footer')?>

      </div>
    </div>
  </div>




<?= $this->insert('overall/footer')?>
<script src="views/app/js/proveedor/crear.js"></script>
</body>

</html>