<!doctype html>
<html lang="es" class="no-js">

<head>
  
  <base href="<?= URL ?>" />

  <meta charset="UTF-8">
  <meta name="application-name" content="<?= APP ?>" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="theme-color" content="#3e454c">

  <link type="image/x-icon" href="views/favicon.ico" rel="shortcut icon" />
  <link href="views/app/images/apple-touch-icon.png" rel="apple-touch-icon-precomposed" />

  <title><?= APP ?></title>

  <!-- Font awesome -->
  <link rel="stylesheet" href="views/admin/css/font-awesome.min.css">
  <!-- Sandstone Bootstrap CSS -->
  <link rel="stylesheet" href="views/admin/css/bootstrap.min.css">
  <!-- Bootstrap Datatables -->
  <link rel="stylesheet" href="views/admin/css/dataTables.bootstrap.min.css">
  <!-- Bootstrap social button library -->
  <link rel="stylesheet" href="views/admin/css/bootstrap-social.css">
  <!-- Bootstrap select -->
  <link rel="stylesheet" href="views/admin/css/bootstrap-select.css">
  <!-- Bootstrap file input -->
  <link rel="stylesheet" href="views/admin/css/fileinput.min.css">
  <!-- Awesome Bootstrap checkbox -->
  <link rel="stylesheet" href="views/admin/css/awesome-bootstrap-checkbox.css">
  <!-- Admin Stye -->
  <link rel="stylesheet" href="views/admin/css/style.css">

  <link rel="stylesheet" href="views/app/css/custom.css" />

  <link rel="stylesheet" href="views/app/css/font-awesome.min.css" />

  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>