
<nav class="ts-sidebar">
      <ul class="ts-sidebar-menu">
        <li class="ts-label">Search</li>
        <li>
          <input type="text" class="ts-sidebar-search" placeholder="Search here...">
        </li>
        <li class="ts-label">Menú</li>
        <!-- <li><a href="index.html"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="#"><i class="fa fa-desktop"></i> UI Elements</a>
          <ul>
            <li><a href="panels.html">Panels and Wells</a></li>
            <li><a href="buttons.html">Buttons</a></li>
            <li><a href="notifications.html">Notifications</a></li>
            <li><a href="typography.html">Typography</a></li>
            <li><a href="icon.html">Icon</a></li>
            <li><a href="grid.html">Grid</a></li>
          </ul>
        </li>
        <li><a href="tables.html"><i class="fa fa-table"></i> Tables</a></li>
        <li><a href="forms.html"><i class="fa fa-edit"></i> Forms</a></li>
        <li><a href="charts.html"><i class="fa fa-pie-chart"></i> Charts</a></li>
        <li><a href="#"><i class="fa fa-sitemap"></i> Multi-Level Dropdown</a>
          <ul>
            <li><a href="#">2nd level</a></li>
            <li><a href="#">2nd level</a></li>
            <li><a href="#">3rd level</a>
              <ul>
                <li><a href="#">3rd level</a></li>
                <li><a href="#">3rd level</a></li>
              </ul>
            </li>
          </ul>
        </li>
        <li class="open"><a href="#"><i class="glyphicon glyphicon-user"></i> Gestion de usuarios</a>
          <ul>
            <li><a href="<?= URL.'users' ?>">Listado</a></li>
            <li><a href="<?= URL.'users/crear' ?>">Crear</a></li>
          </ul>
        </li> -->


        <?php if(false!=$_SESSION['MENU']):?>
          <?php foreach ($_SESSION['MENU'] as &$pag):?>
            <li><a href="<?= URL.$pag['pagurl']?>"><i class="<?=$pag['pagicono']?>"></i> <?=$pag['pagname']?></a>
            <?php $primero=true; ?>
                <?php if(false!=$_SESSION['MENUHIJOS']):?>
                  <?php foreach ($_SESSION['MENUHIJOS'] as &$hijo):?>
                    <?php if($pag['nivel']==explode(".", $hijo['nivel'])[0]): ?>
                      <?= $primero?'<ul>':'' ?>
                      <li><a href="<?= URL.$hijo['pagurl'] ?>"><?=$hijo['pagname']?></a></li>
                      <?php $primero=false; ?>
                    <?php endif ?>
                  <?php endforeach  ?>
                  <?= !$primero?'</ul>':'' ?>
                <?php endif  ?>
            </li>
          <?php endforeach  ?>
        <?php endif  ?>

        <!-- Account from above -->
        <ul class="ts-profile-nav">
          <li><a href="#">Ayuda</a></li>
          <li><a href="#">Settings</a></li>
          <li class="ts-account">
            <a href="#"><img src="views/admin/img/ts-avatar.jpg" class="ts-avatar hidden-side" alt=""> Account <i class="fa fa-angle-down hidden-side"></i></a>
            <ul>
              <li><a href="#">My Account</a></li>
              <li><a href="#">Edit Account</a></li>
              <li><a href="<?= URL.'logout/' ?>">Logout</a></li>
            </ul>
          </li>
        </ul>

      </ul>
    </nav>