<?= $this->insert('overall/header')?>

<body>

<?= $this->insert('overall/topnav')?>

  <div class="ts-main-content">

    <?= $this->insert('overall/menu')?>

    <div class="content-wrapper">
      <div class="container-fluid">

        <div class="row">
          <div class="col-md-12">
          
            <h1 class="page-title">Producto</h1>

            <h2>Edición</h2>
            
            <div class="col-lg-2"></div>
            <div class="well col-lg-8">
              <div class="form-actions">
                <div class="panel panel-default">
                  <div class="panel-heading">Editar Producto</div>
                  <div class="panel-body">

                    <form id="producto_form" role="form">

                      <input type="hidden" name="proCodigoBarra" value="<?= $data['proCodigoBarra'] ?>" />

                      <div class="alert hide" id="ajax_producto"></div>
                      <div class="form-group">
                        <label class="cole">Ejemplo:</label>
                        <input type="text" class="form-control form-input" name="ejemplo" value="<?= $data['ejemplo'] ?>" placeholder="Escribe algo..." />
                      </div>
                      <div class="col-lg-12">
                        <div class="form-group">
                          <button type="button" id="producto" class="btn btn-primary  center-block">Enviar</button>
                        </div>
                      </div>
                    </form>

                  </div>
                </div>
              </div>
              <a class="btn btn-primary" href="producto">Ver listado</a>
            </div>
            <div class="col-lg-2"></div> 

            
          </div>
        </div>
        
        <?= $this->insert('overall/inner_footer')?>

      </div>
    </div>
  </div>

<?= $this->insert('overall/footer')?>
<script src="views/app/js/producto/editar.js"></script>
</body>

</html>