<?= $this->insert('overall/header')?>

<body>

<div class="login-page bk-img" style="background-image: url(views/admin/img/login-bg.jpg);">
    <div class="form-content">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <h1 class="text-center text-bold text-light mt-4x">Iniciar sesión</h1>
            <div class="well row pt-2x pb-3x bk-light">
              <div class="col-md-8 col-md-offset-2">
                <form role="form" enctype="application/x-www-form-urlencoded" id="login_form" class="mt">

                  <div class="alert hide" id="ajax_login"></div>

                  <div class="form-group">
                    <label for="" class="text-uppercase text-sm">Usuario:</label>
                    <input type="text" name="user" class="form-control  mb" required="" />
                  </div>
                  <div class="form-group">
                    <label for="" class="text-uppercase text-sm">Contraseña:</label>
                    <input type="password" name="pass" class="form-control  mb" required="" />
                  </div>

                  <button class="btn btn-primary btn-block" type="button" id="login">INICIAR SESIÓN</button>
                </form>
              </div>
            </div>
            <div class="text-center text-light">
              <a href="#" class="text-light" data-toggle="modal" data-target="#lost_pass">Contraseña Perdida</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


<?= $this->insert('overall/lostpass') ?>

<?= $this->insert('overall/footer')?>

</body>

</html>