<?= $this->insert('overall/header')?>

<body>

<?= $this->insert('overall/topnav')?>

  <div class="ts-main-content">

    <?= $this->insert('overall/menu')?>

    <div class="content-wrapper">
      <div class="container-fluid">

        <div class="row">
          <div class="col-md-12">
          
            <h1 class="page-title">Marca</h1>

            <h2>Listado</h2>
            
            <div class="well">
              <div class="form-actions">

                <div class="panel-heading">LISTADO DE MARCAS</div>
                  <div class="panel-body">
                    <table id="zctb" class="display table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Nombre</th>
                          <th>Descripción</th>
                          <th>Estado</th>
                          <?php  if(false!=$edita): ?>
                          <th></th>
                          <?php  endif ?>
                          <?php  if(false!=$elimina): ?>
                          <th></th>
                          <?php  endif ?>
                        </tr>
                      </thead>
                      <tfoot>
                        <tr>
                          <th>#</th>
                          <th>Nombre</th>
                          <th>Descripción</th>
                          <th>Estado</th>
                          <?php  if(false!=$edita): ?>
                          <th></th>
                          <?php  endif ?>
                          <?php  if(false!=$elimina): ?>
                          <th></th>
                          <?php  endif ?>
                        </tr>
                      </tfoot>
                      <tbody>
                        <?php foreach(false != $data ? $data : array() as $d): ?>
                        <tr>
                          <td><?= $d['marCodigo'] ?></td>
                          <td><?= $d['marNombre'] ?></td>
                          <td><?= $d['marDescripcion'] ?></td>
                          <td><?= $d['marEstado']=='AC'?'Activo':'Inactivo' ?></td>
                          <?php  if(false!=$edita): ?>
                          <td><a href="marca/editar/<?= $d['marCodigo'] ?>">Editar</a></td>
                          <?php  endif ?>
                          <?php  if(false!=$elimina): ?>
                          <td><a href="marca/eliminar/<?= $d['marCodigo'] ?>">Eliminar</a></td>
                          <?php  endif ?>
                        </tr>
                        <?php endforeach ?>
                        </tbody>
                    </table>
                    <?php  if(false!=$crea): ?>
                     <a class="btn btn-primary" href="marca/crear">Crear</a>
                    <?php  endif ?>
                
              </div>
            </div>
            
          </div>
        </div>
        
        <?= $this->insert('overall/inner_footer')?>

      </div>
    </div>
  </div>

<?= $this->insert('overall/footer')?>

</body>

</html>