<?= $this->insert('overall/header')?>

<body>

<?= $this->insert('overall/topnav')?>

  <div class="ts-main-content">

    <?= $this->insert('overall/menu')?>

    <div class="content-wrapper">
      <div class="container-fluid">

        <div class="row">
          <div class="col-md-12">
          
            <h2 class="page-title">Permisos</h2>
            
            <!-- <div class="well"> -->
              <form id="permisos_form" role="form">
                  <div class="alert hide" id="ajax_permisos"></div>
                  <div class="row">
                     <div class="col-xs-4"></div>
                      <div class="col-lg-4 form-group">
                            <label class="cole">Rol:</label>
                            
                            <?= Bootstrap::basic_select('rol',$roles, false, '0', 'rol') ?>
                      </div>
                      <div class="col-xs-4"></div>
                  </div>
                 
                  <div class="row">
                    <div class="col-xs-3"></div>
                     <div class="col-xs-6">
                        <h3 class="text-center">Listado de páginas permitidas</h3>
                        <div class="well" style="max-height: 300px;overflow: auto;">
                          <ul id="check-list-box" class="list-group checked-list-box">
                          <?php foreach ($paginas as $pag): ?>
                              <li class="list-group-item" data-id="<?= $pag['pagid'] ?>"  data-color="info"><?= $pag['pagname'] ?> 
                                <select class="form-group">
                                  <option value="">Solo visualización</option>
                                  <option value="edita">Edita</option>
                                  <option value="elimina">Elimina</option>
                                  <option value="edyel">Edita y elimina</option>
                                </select>
                              </li>
                            <?php endforeach  ?>
                          </ul>
                        </div>
                        <!-- <pre id="display-json"></pre> -->
                      </div>
                    <div class="col-xs-3"></div>
                  </div>

                  
                  <div class="form-group">
                    <button type="button" id="permisos" class="btn btn-primary  center-block">Enviar</button>
                  </div>
              </form>

            <!-- </div> -->
            
          </div>
        </div>
        
        <?= $this->insert('overall/inner_footer')?>

      </div>
    </div>
  </div>




<?= $this->insert('overall/footer')?>
<script src="views/app/js/permisos.js"></script>
</body>

</html>