<?= $this->insert('overall/header')?>

<body>

<?= $this->insert('overall/topnav')?>

  <div class="ts-main-content">

    <?= $this->insert('overall/menu')?>

    <div class="content-wrapper">
      <div class="container-fluid">

        <div class="row">
          <div class="col-md-12">
          
            <h1 class="page-title">Users</h1>

            <h2>Edición</h2>
            
            <div class="col-lg-2"></div>
            <div class="well col-lg-8">
              <div class="form-actions">
                <div class="panel panel-default">
                  <div class="panel-heading">Editar usuario</div>
                  <div class="panel-body">
                <form id="users_form" role="form">

                  <input type="hidden" name="id" value="<?= $data['userid'] ?>" />

                  <div class="alert hide" id="ajax_users"></div>
                  

                    <div class="col-lg-4 form-group">
                        <label class="cole">Nro. Cédula:</label>
                        <input type="text" class="form-control form-input" name="cedula" value="<?= $data['userdoc'] ?>" placeholder="Escriba el nro de cédula..." />
                      </div>

                      <div class="col-lg-4 form-group">
                        <label class="cole">Nombre:</label>
                        <input type="text" class="form-control form-input" name="nombre" value="<?= $data['username'] ?>" placeholder="Escriba el nombre..." />
                      </div>

                      <div class="col-lg-4 form-group">
                        <label class="cole">Teléfono:</label>
                        <input type="text" class="form-control form-input" name="telefono" value="<?= $data['usertele'] ?>" placeholder="Escriba el telefono..." />
                      </div>

                      <div class="col-lg-4 form-group">
                        <label class="cole">Dirección:</label>
                        <input type="text" class="form-control form-input" name="direccion" value="<?= $data['userdir'] ?>" placeholder="Escriba la dirección..." />
                      </div>

                      <div class="col-lg-4 form-group">
                        <label class="cole">Correo:</label>
                        <input type="text" class="form-control form-input" name="correo" value="<?= $data['usercorreo'] ?>" placeholder="Escriba el correo..." />
                      </div>

                      <div class="col-lg-4 form-group">
                        <label class="cole">Usuario:</label>
                        <input type="text" class="form-control form-input" name="usuario" value="<?= $data['userusu'] ?>" placeholder="Escriba el usuario..." />
                      </div>

                      <div class="col-lg-4 form-group">
                        <label class="cole">Sucursal:</label>
                        
                        <?= Bootstrap::basic_select('sucursal',$sucursal, false, $data['sucursal']??0, 'form-control') ?>
                      </div>

                      <div class="col-lg-4 form-group">
                        <label class="cole">Rol:</label>
                        
                        <?= Bootstrap::basic_select('rol',$roles, false, $data['rol']??0, 'form-control') ?>
                      </div>

                      <div class="col-lg-12">
                        <div class="checkbox checkbox-info checkbox-circle">
                          <input id="editpass" type="checkbox" name="editpass">
                          <label for="editpass">
                            Editar contraseña
                          </label>
                        </div>
                      </div>

                      <div class="col-lg-4 form-group">
                        
                        <label class="cole">Contraseña:</label>
                        <input type="password" class="form-control form-input txtpass" name="pass" disabled placeholder="Escriba la contraseña..." />
                      </div>

                      <div class="col-lg-4 form-group">
                        <label class="cole">Repetir contraseña:</label>
                        <input type="password" class="form-control form-input txtpass" name="pass2" disabled placeholder="Escriba otra vez contraseña..." />
                      </div>

                      <div class="col-lg-4 form-group">
                        <label class="cole">Estado:</label>
                        <select class="form-control" name="estado">
                          <option value="AC">Activo</option>
                          <option value="IN">Inactivo</option>
                        </select> 
                      </div>
                  <div class="col-lg-12">
                        <div class="form-group">
                          <button type="button" id="users" class="btn btn-primary  center-block">Enviar</button>
                        </div>
                      </div>
                </form>

                </div>
                </div>

              </div>
              <a class="btn btn-primary" href="users">Ver listado</a>
            </div>
            <div class="col-lg-2"></div>
            
          </div>
        </div>
        
        <?= $this->insert('overall/inner_footer')?>

      </div>
    </div>
  </div>

<?= $this->insert('overall/footer')?>
<script src="views/app/js/users/editar.js"></script>
</body>

</html>