<?= $this->insert('overall/header')?>

<body>

<?= $this->insert('overall/topnav')?>

  <div class="ts-main-content">

    <?= $this->insert('overall/menu')?>

    <div class="content-wrapper">
      <div class="container-fluid">

        <div class="row">
          <div class="col-md-12">
          
            <h1 class="page-title">Usuarios</h1>

            <h2>Listado</h2>
            
            <div class="well">
              <div class="form-actions">
                <!-- Zero Configuration Table -->
            <div class="panel panel-default">
              <div class="panel-heading">Listado de usuarios</div>
              <div class="panel-body">
                <table id="zctb" class="display table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                  <thead>
                  <tr>
                      <th>#</th>
                      <th>Nombre</th>
                      <th>Cédula</th>
                      <th>Usuario</th>
                      <th>Teléfono</th>
                      <th>Dirección</th>
                      <th>Correo</th>
                      <th>Sucursal</th>
                      <th>Rol</th>
                      <th>Estado</th>
                      <th></th>
                      <th></th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>#</th>
                      <th>Nombre</th>
                      <th>Cédula</th>
                      <th>Usuario</th>
                      <th>Teléfono</th>
                      <th>Dirección</th>
                      <th>Correo</th>
                      <th>Sucursal</th>
                      <th>Rol</th>
                      <th>Estado</th>
                      <th></th>
                      <th></th>
                    </tr>
                  </tfoot>
                  <tbody>
                  <?php foreach(false != $data ? $data : array() as $d): ?>
                  <tr>
                    <td><?= $d['userid'] ?></td>
                    <td><?= $d['username'] ?></td>
                    <td><?= $d['userdoc'] ?></td>
                    <td><?= $d['userusu'] ?></td>
                    <td><?= $d['usertele'] ?></td>
                    <td><?= $d['userdir'] ?></td>
                    <td><?= $d['usercorreo'] ?></td>
                    <td><?= $d['sucname'] ?></td>
                    <td><?= $d['rolname'] ?></td>
                    <td><?= $d['userestado']=='AC'?'Activo':'Inactivo' ?></td>
                    <td><a href="users/editar/<?= $d['userid'] ?>">Editar</a></td>
                    <td><a href="users/eliminar/<?= $d['userid'] ?>">Eliminar</a></td>
                  </tr>
                  <?php endforeach ?>
                  </tbody>
                </table>
                <a class="btn btn-primary" href="users/crear">Crear</a>
              </div>
            </div>
            
          </div>
        </div>
        
        <?= $this->insert('overall/inner_footer')?>

      </div>
    </div>
  </div>

<?= $this->insert('overall/footer')?>

</body>

</html>